### ISSUE TITLE
Number of connected clients

### ISSUE THREAD

**Issue by JoergBe** [vallahaye/docker-nginx-rtmp#2]
Hello,
I use the image and it has everything I need. Almost at least :-) Is there any way to find out how many clients have connected to VLC?

**Comment by vallahaye** [comment]
Hello,

This section of the wiki seems to cover what you want to do: [Getting number of subscribers](https://github.com/arut/nginx-rtmp-module/wiki/Getting-number-of-subscribers)

Kind regards
